# naive bayes algorithm
Naive base algorith is a classification technique based on Bayes' Theorem with an assumption of independence among predictors. In simple terms, a Naive Bayes classifier assumes that the presence of a particular feature in a class is unrelated to the presence of any other feature. For example, a fruit may be considered to be an apple if it is red, round, and about 3 inches in diameter. Even if these features depend on each other or upon the existence of the other features, a naive Bayes classifier would consider all of these properties to independently contribute to the probability that this fruit is an apple.
# Bayes' Theorem
Bayes' theorem is a mathematical formula used for calculating conditional probabilities. It can be used to determine the probability of a hypothesis given our prior knowledge. Mathematically, it is expressed as:
P(A|B) = P(B|A) * P(A) / P(B)
Where:
- P(A|B) is the probability of hypothesis A given the data B.
- P(B|A) is the probability of data B given that the hypothesis A was true.
- P(A) is the probability of hypothesis A being true.
- P(B) is the probability of data B being true.
- P(A) and P(B) are the independent probabilities of A and B.
- P(B|A) is the likelihood of B given A.
- P(A|B) is the posterior probability of A given B.
- P(B|A) * P(A) is the prior probability of A given B.
- P(B) is the prior probability of B.
# Naive Bayes Classifier
Naive Bayes classifier is a probabilistic classifier based on Bayes' theorem with an assumption of independence among predictors. It is a simple and effective algorithm for classification problems. The Naive Bayes classifier is based on the following assumptions:

In [1]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.datasets import load_iris

In [2]:
# laod the datasets
data = load_iris()
x = data.data
y = data.target

# split the data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [3]:
# model initiates
gnb = GaussianNB()

# train the model
gnb.fit(x_train, y_train)

# predict the model
y_pred = gnb.predict(x_test)

# evaluate the model
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [4]:
#model initiates
mnb = MultinomialNB()

# train the model
mnb.fit(x_train, y_train)

# predict the model
y_pred = mnb.predict(x_test)

# evaluate the model
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9
[[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30



In [5]:
# model initiates
bnb = BernoulliNB()

# train the model
bnb.fit(x_train, y_train)

# predict the model
y_pred = bnb.predict(x_test)

# evaluate the model
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.3
[[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.30      1.00      0.46         9
           2       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30



c:\Users\dell\miniconda3\envs\mlpractice\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\dell\miniconda3\envs\mlpractice\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\dell\miniconda3\envs\mlpractice\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(r